#pragma once

#define IDC_STATIC (-1)

#define IDI_APP_ICON 1

#define IDD_SETTINGS_DIALOG 100
#define IDC_LLAMA_MODEL 101
#define IDC_BROWSE_LLAMA 102
#define IDC_KOKORO_VOICE 103
#define IDC_AVATAR_SONNY 104
#define IDC_AVATAR_IRONMAN 105
#define IDC_SYSTEM_PROMPT 106
#define IDC_USE_BROWSER_STT 107
#define IDC_USE_BROWSER_TTS 108
#define IDC_BROWSER_VOICE 109
#define IDC_SHOW_AVATAR 110
#define IDC_RAG_EMBEDDING_MODEL 111
#define IDC_BROWSE_RAG_MODEL 112
#define IDC_WAKE_WORD_ENABLED 113
#define IDC_DEBUG_MODE 114
#define IDC_LANGUAGE 115
#define IDC_TTS_SPEED 116
#define IDC_MIC_GAIN 119

// Retrieval budget + the opt-in peer metrics network.
#define IDC_RAG_CONTEXT_BUDGET 120
#define IDC_VECTORS_ENABLED 121
#define IDC_VECTORS_MODE 122
#define IDC_VECTORS_ROOM 123
#define IDC_VECTORS_RELAY 124
#define IDC_VECTORS_SHARE_METRICS 125

// Compiled-in RAG embedding model (optional; see SONNY_EMBED_MODEL_FILE in
// CMakeLists.txt). Both resources are present only in builds that embed a model.
#define IDR_EMBEDDING_MODEL 300
#define IDR_EMBEDDING_VOCAB 301

#define IDD_FIRST_RUN_WIZARD 200
#define IDC_WIZARD_MODEL 201
#define IDC_WIZARD_BROWSE_MODEL 202
#define IDC_WIZARD_VOICE 203
#define IDC_WIZARD_AVATAR_SONNY 204
#define IDC_WIZARD_AVATAR_IRONMAN 205
#define IDC_WIZARD_LANGUAGE 206
#define IDC_WIZARD_SKIP 207

// Tabbed settings dialog
#define IDD_SETTINGS_TABBED 300
#define IDC_SETTINGS_TAB 301

// Tab page dialogs
#define IDD_TAB_AI_VOICE 310
#define IDD_TAB_BROWSER_STT_TTS 311
#define IDD_TAB_AVATAR_PROMPT 312
#define IDD_TAB_RAG_ENGINE 313
#define IDD_TAB_VECTORS 314

// Tab page controls (offset by page * 10 to avoid conflicts)
#define IDC_TAB_AI_VOICE_LLAMA_MODEL 320
#define IDC_TAB_AI_VOICE_BROWSE_LLAMA 321
#define IDC_TAB_AI_VOICE_KOKORO_VOICE 322
#define IDC_TAB_AI_VOICE_LANGUAGE 323
#define IDC_TAB_AI_VOICE_TTS_SPEED 324
#define IDC_TAB_AI_VOICE_MIC_GAIN 325

#define IDC_TAB_BROWSER_STT 330
#define IDC_TAB_BROWSER_TTS 331
#define IDC_TAB_BROWSER_VOICE 332

#define IDC_TAB_AVATAR_SHOW 340
#define IDC_TAB_AVATAR_SONNY 341
#define IDC_TAB_AVATAR_IRONMAN 342
#define IDC_TAB_AVATAR_SYSTEM_PROMPT 343
#define IDC_TAB_VISION_CAMERA_ENABLED 344
#define IDC_TAB_VISION_CAMERA_DEVICE 345

#define IDC_TAB_RAG_EMBEDDING_MODEL 350
#define IDC_TAB_RAG_BROWSE_MODEL 351
#define IDC_TAB_RAG_WAKE_WORD 352
#define IDC_TAB_RAG_DEBUG_MODE 353
#define IDC_TAB_RAG_CONTEXT_BUDGET 354

#define IDC_TAB_VECTORS_ENABLED 360
#define IDC_TAB_VECTORS_MODE 361
#define IDC_TAB_VECTORS_ROOM 362
#define IDC_TAB_VECTORS_RELAY 363
#define IDC_TAB_VECTORS_SHARE_METRICS 364

